apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-access-gateway.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30080
      {{- end }}
  selector:
    app: {{ include "inventory-access-gateway.name" . }}